stages:
  - build
  - deploy

variables:
  SERVICE_NAME: "esg-web"
  TAR_FILE: "${SERVICE_NAME}-bak" # Định nghĩa biến tên tệp bak

cache:
  paths:
    - node_modules

# Giai đoạn build cho ứng dụng front-end
build:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 day
  only:
    - main

deploy:
  stage: deploy
  before_script:
    - "which ssh-agent || ( apk add --update --no-cache openssh )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H 192.168.40.105 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
  # Xóa thư mục backup cũ
  - ssh administrator@192.168.40.105 "rm -rf /home/administrator/Docker/Nginx/nginx_html/${SERVICE_NAME}-bak"

  # Backup thư mục cũ (nếu có)
  - ssh administrator@192.168.40.105 "[ -d /home/administrator/Docker/Nginx/nginx_html/${SERVICE_NAME} ] && mv /home/administrator/Docker/Nginx/nginx_html/${SERVICE_NAME} /home/administrator/Docker/Nginx/nginx_html/${SERVICE_NAME}-bak"

  # Đổi tên thư mục build và upload lên server
  - mv dist ${SERVICE_NAME}
  - scp -r ${SERVICE_NAME} administrator@192.168.40.105:/home/administrator/Docker/Nginx/nginx_html/

  # Dừng và xóa container cũ (nếu có)
  - ssh administrator@192.168.40.105 "docker stop ${SERVICE_NAME} 2>/dev/null || true"
  - ssh administrator@192.168.40.105 "docker rm ${SERVICE_NAME} 2>/dev/null || true"

  # Xóa container Nginx cũ nếu có
  - ssh administrator@192.168.40.105 "docker stop nginx 2>/dev/null || true"
  - ssh administrator@192.168.40.105 "docker rm nginx 2>/dev/null || true"

  # Chạy container Nginx mới
  - ssh administrator@192.168.40.105 "docker run -d --name ${SERVICE_NAME} -p 3000:80 \
      -v /home/administrator/Docker/Nginx/nginx_config/nginx.conf:/etc/nginx/conf.d/default.conf:ro \
      -v /home/administrator/Docker/Nginx/nginx_html/${SERVICE_NAME}:/usr/share/nginx/html:ro \
      nginx:latest"
  retry: 2
  only:
    - main
