stages:
  - build
  - deploy

variables:
  SERVICE_NAME: "esg-web"
  TAR_FILE: "${SERVICE_NAME}-bak" # Định nghĩa biến tên tệp bak

cache:
  paths:
    - node_modules

# Giai đoạn build cho ứng dụng front-end
build:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 day
  only:
    - main

deploy:
  stage: deploy
  before_script:
    - "which ssh-agent || ( apk add --update --no-cache openssh )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H 192.168.40.105 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    # Di chuyển thư mục cũ và tạo bản sao lưu
    - ssh administrator@192.168.40.105 "rm -rf /home/administrator/Docker/Nginx/nginx_html/${SERVICE_NAME}-bak"
    - ssh administrator@192.168.40.105 "if [ -d /home/administrator/Docker/Nginx/nginx_html/${SERVICE_NAME} ]; then mv /home/administrator/Docker/Nginx/nginx_html/${SERVICE_NAME} /home/administrator/Docker/Nginx/nginx_html/${SERVICE_NAME}-bak; fi"

    # Đổi tên thư mục dist thành tên dịch vụ (nếu cần)
    - mv dist ${SERVICE_NAME}   # Đổi tên dist thành tên dịch vụ

    # Chuyển thư mục đã đổi tên đến server
    - scp -r ${SERVICE_NAME} administrator@192.168.40.105:/home/administrator/Docker/Nginx/nginx_html/

    # Kiểm tra và dừng dịch vụ ${SERVICE_NAME} nếu đang chạy
    - ssh administrator@192.168.40.105 "docker ps -q --filter name=${SERVICE_NAME} | xargs -r docker stop"
    - ssh administrator@192.168.40.105 "docker ps -a -q --filter name=${SERVICE_NAME} | xargs -r docker rm"

    # Dừng và xóa container Nginx cũ nếu có
    - ssh administrator@192.168.40.105 "docker ps -q --filter name=nginx | xargs -r docker stop"
    - ssh administrator@192.168.40.105 "docker ps -a -q --filter name=nginx | xargs -r docker rm"

    # Khởi động container Nginx mới với thư mục nginx_html là thư mục tĩnh
    - ssh administrator@192.168.40.105 "docker run -d --name nginx -p 3000:80 -v /home/administrator/Docker/Nginx/nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro -v /home/administrator/Docker/Nginx/nginx_html/${SERVICE_NAME}:/usr/share/nginx/html:ro nginx:latest"
  retry: 2
  only:
    - main
